services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db/data:/var/opt/mssql/data